services:
  web:
    image: ghcr.io/theo1335/flask-docker:latest
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
    networks:
      - proxy
      - internal
    labels:
      - "traefik.docker.network=proxy"
      - "traefik.enable=true"
      - "traefik.http.routers.flask-https.rule=Host(`flask.theo-massenya.fr`)"
      - "traefik.http.routers.flask-https.entrypoints=websecure"
      - "traefik.http.routers.flask-https.tls.certresolver=letsencrypt"
      - "traefik.http.routers.flask-https.service=flask"
      - "traefik.http.services.flask.loadbalancer.server.port=5000"
      - "traefik.http.routers.flask-http.rule=Host(`flask.theo-massenya.fr`)"
      - "traefik.http.routers.flask-http.entrypoints=web"
      - "traefik.http.routers.flask-http.middlewares=redirect-to-https@file"
  db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal
      
volumes:
  postgres_data:

networks:
  proxy:
    external: true
  internal:
    driver: bridge