name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  buil-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: recuperation de code
      - uses: actions/checkout@v3

      - name: Connection à ghcr.io
      - run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u theo1335 --password-stdin
      
      - name: Build et push de l'image
      - run: |
          docker build -t ghcr.io/theo1335/flask-docker:latest .
          docker push ghcr.io/theo1335/flask-docker:latest