name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: recuperation de code
        uses: actions/checkout@v5

      - name: Connection à ghcr.io
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u theo1335 --password-stdin
      
      - name: Build et push de l'image
        run: |
          docker build -t ghcr.io/theo1335/flask-docker:latest .
          docker push ghcr.io/theo1335/flask-docker:latest
      
      - name: Deploiment sur VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd ~/docker_app/flask-app
            docker compose pull
            docker compose up -d --remove-orphans
            docker image prune -f